export const initialState = {
  userName: "randi",
  email: "nothing@email.com",
  photo: "",
  homeTown: "nowhere",
  currentLocation: {
    country: "nowhere",
    city: "nowhere",
  },
  activeRoute: "",
  lastOnline: "",
  rank: 0,
  xp: "",
  level: "",
  playing: false,
  currentGame: "none",
  gamesPlayed: [],
  totalGameTime: 0,
  totalGamesPlayed: 398,
  winRate: 96.6,
  loseRate: 4.4,
  wins: 77,
  ties: 21,
  loses: 15,
  badges: ["fast", "perfect", "determined"],
  isLoggedIn: { userId: null, status: false, token: null },
};
