export const initialState = {
  userName: "randi",
  email: "nothing@email.com",
  photo: "",
  homeTown: "nowhere",
  currentLocation: {
    country: "nowhere",
    city: "nowhere",
  },
  activeRoute: "",
  lastOnline: "",
  rank: "",
  xp: "",
  level: "",
  playing: false,
  currentGame: "none",
  gamesPlayed: [],
  totalGameTime: 0,
  totalGamesPlayed: "",
  winRate: 0,
  loseRate: 0,
  wins: 0,
  ties: 0,
  loses: 0,
  badges: [],
  isLoggedIn: { userId: null, status: false, token: null },
};
